### ISSUE TITLE
Possible typo in the docs of `rhohat.lpp`

### ISSUE THREAD

**Issue by agila5** [spatstat/spatstat.linnet#5]
Dear developers, the documentation of `rhohat.lpp` says the following:  

https://github.com/spatstat/spatstat.linnet/blob/c04b9d63562f93f7fb77f8029aef250c30245c24/man/rhohat.lpp.Rd#L211-L216 

Maybe I don't understand something, but I think that the doc should be slightly updated since `intensity.quadratcount` or `quadratcount` cannot be run with `lpp` objects: 

``` r
library(spatstat)
#> Loading required package: spatstat.data
#> Loading required package: spatstat.geom
#> spatstat.geom 2.2-2
#> Loading required package: spatstat.core
#> Loading required package: nlme
#> Loading required package: rpart
#> spatstat.core 2.3-0
#> Loading required package: spatstat.linnet
#> spatstat.linnet 2.3-0
#> 
#> spatstat 2.2-0       (nickname: 'That's not important right now') 
#> For an introduction to spatstat, type 'beginner'
Y <- runiflpp(30, simplenet)
quadratcount(Y)
#> Error in UseMethod("quadratcount"): no applicable method for 'quadratcount' applied to an object of class "c('lpp', 'ppx')"
```

<sup>Created on 2021-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by baddstats** [comment]
Thanks for your message. 

In your example you tried `quadratcount(Y)`, but the document does not say that `quadratcount(Y)` will work. It says that `quadratcount(Y, tess=covariate)` will work, where `covariate` is a factor-valued covariate. That is currently not true either (sorry!) but it will be true in a future release of `spatstat.linnet`. To avoid confusion, I will remove this text from the help file, for now.

**Comment by agila5** [comment]
Dear Prof. Baddeley, thank you very much for your explanation.

Andrea
